---
- name: Create a sonarqube container
  docker_container:
    name: sonar
    image: sonarqube
    restart_policy: always
    volumes:
     - /efs/dc/rec/shr/app/sonar/prd/data:/opt/sonarqube/data rw
     - /efs/dc/rec/shr/app/sonar/prd/conf:/opt/sonarqube/conf rw
    ports:
     - "9000:9000"
     - "9092:9092"
