---
- name: Install python-pip
  yum:
    name: python-pip
    state: present

- name:  Check version of pip
  pip:
   name: pip
   version: 9.0.1

#- name: Check pip version
#  command: pip -V
#  register: pip_version
#  ignore_errors: true

#- name: Upgrade pip
#  pip:
#    name: pip
#    extra_args: --upgrade
#  when: pip_version.stdout.find('pip 9.0') == -1

- name: Install docker-py module
  pip:
   name: docker-py
   state: present
